package yamenko.abcgrocery.views;

import javax.swing.GroupLayout;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.WindowConstants;
import yamenko.abcgrocery.views.components.MainViewComponents;

/**
 *
 * @author Eugene Yamenko <yamenko@me.com>
 */
public class MainView extends javax.swing.JFrame implements View<MainViewComponents> {
    @Override
    public Object getComponent(MainViewComponents component) {
        switch (component) {
            case ProductsItem:
                return productsItem;
            case RequirementsItem:
                return requirementsItem;
            case SaleActivitiesItem:
                return saleActivitiesItem;
            case SuppliersItem:
                return suppliersItem;
            default:
                return null;
        }
    }

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMenuBar = new JMenuBar();
        menu = new JMenu();
        productsItem = new JMenuItem();
        suppliersItem = new JMenuItem();
        requirementsItem = new JMenuItem();
        saleActivitiesItem = new JMenuItem();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("ABCGrocery");
        setLocationByPlatform(true);
        setResizable(false);

        mainMenuBar.setName("mainMenuBar"); // NOI18N

        menu.setText("Menu");
        menu.setName("menu"); // NOI18N

        productsItem.setText("Products");
        productsItem.setName("productsItem"); // NOI18N
        menu.add(productsItem);

        suppliersItem.setText("Suppliers");
        suppliersItem.setName("suppliersItem"); // NOI18N
        menu.add(suppliersItem);

        requirementsItem.setText("Requirements");
        requirementsItem.setName("requirementsItem"); // NOI18N
        menu.add(requirementsItem);

        saleActivitiesItem.setText("Sale activities");
        saleActivitiesItem.setName("saleActivitiesItem"); // NOI18N
        menu.add(saleActivitiesItem);

        mainMenuBar.add(menu);

        setJMenuBar(mainMenuBar);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public JMenuBar mainMenuBar;
    public JMenu menu;
    public JMenuItem productsItem;
    public JMenuItem requirementsItem;
    public JMenuItem saleActivitiesItem;
    public JMenuItem suppliersItem;
    // End of variables declaration//GEN-END:variables
}
