package yamenko.abcgrocery.views;

import java.awt.Dimension;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.Binding;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.beansbinding.Bindings;
import org.jdesktop.beansbinding.ELProperty;
import org.jdesktop.observablecollections.ObservableCollections;
import org.jdesktop.observablecollections.ObservableList;
import org.jdesktop.swingbinding.JComboBoxBinding;
import org.jdesktop.swingbinding.JTableBinding;
import org.jdesktop.swingbinding.SwingBindings;
import yamenko.abcgrocery.entities.Quotation;
import yamenko.abcgrocery.entities.Supplier;
import yamenko.abcgrocery.views.components.QuotationViewComponents;

/**
 *
 * @author Eugene Yamenko <yamenko@me.com>
 */
public class QuotationView extends javax.swing.JPanel implements View<QuotationViewComponents> {
    private ObservableList<Quotation> quotations = ObservableCollections.observableList(
            new ArrayList<Quotation>());
    private ObservableList<Supplier> suppliers = ObservableCollections.observableList(
            new ArrayList<Supplier>());
    private Quotation quotation = new Quotation();

    public List<Quotation> getQuotations() {
        return quotations;
    }

    public Quotation getQuotation() {
        return quotation;
    }

    public ObservableList<Supplier> getSuppliers() {
        return suppliers;
    }

    /**
     * Creates new form QuotationView
     */
    public QuotationView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new BindingGroup();

        newQuotationLabel = new JLabel();
        quantityField = new JTextField();
        unitPriceField = new JTextField();
        createQuotationButton = new JButton();
        jScrollPane1 = new JScrollPane();
        quotationTable = new JTable();
        quotationListLabel = new JLabel();
        jSeparator1 = new JSeparator();
        purchaseQuotationButton = new JButton();
        suppliersComboBox = new JComboBox();

        setPreferredSize(new Dimension(700, 450));

        newQuotationLabel.setText("Create a new quotation");
        newQuotationLabel.setName("newQuotationLabel"); // NOI18N

        quantityField.setToolTipText("Quantity");
        quantityField.setName("quantityField"); // NOI18N

        Binding binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${quotation.quantity}"), quantityField, BeanProperty.create("text"), "quantityField");
        bindingGroup.addBinding(binding);

        unitPriceField.setToolTipText("Unit price");
        unitPriceField.setName("unitPriceField"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${quotation.unitPrice}"), unitPriceField, BeanProperty.create("text"), "unitPriceField");
        bindingGroup.addBinding(binding);

        createQuotationButton.setText("Create");
        createQuotationButton.setEnabled(false);
        createQuotationButton.setName("createQuotationButton"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        quotationTable.setName("quotationTable"); // NOI18N
        quotationTable.getTableHeader().setReorderingAllowed(false);

        ELProperty eLProperty = ELProperty.create("${quotations}");
        JTableBinding jTableBinding = SwingBindings.createJTableBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, quotationTable);
        JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(ELProperty.create("${id}"));
        columnBinding.setColumnName("Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(ELProperty.create("${quantity}"));
        columnBinding.setColumnName("Quantity");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(ELProperty.create("${supplier}"));
        columnBinding.setColumnName("Supplier");
        columnBinding.setColumnClass(Supplier.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(ELProperty.create("${unitPrice}"));
        columnBinding.setColumnName("Unit Price");
        columnBinding.setColumnClass(BigDecimal.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(quotationTable);
        if (quotationTable.getColumnModel().getColumnCount() > 0) {
            quotationTable.getColumnModel().getColumn(0).setResizable(false);
            quotationTable.getColumnModel().getColumn(1).setResizable(false);
            quotationTable.getColumnModel().getColumn(2).setResizable(false);
            quotationTable.getColumnModel().getColumn(3).setResizable(false);
        }

        quotationListLabel.setText("List of the quotations");
        quotationListLabel.setName("quotationListLabel"); // NOI18N

        jSeparator1.setName("jSeparator1"); // NOI18N

        purchaseQuotationButton.setText("Purchase quotation");
        purchaseQuotationButton.setEnabled(false);
        purchaseQuotationButton.setName("purchaseQuotationButton"); // NOI18N

        suppliersComboBox.setModel(new DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        suppliersComboBox.setName("suppliersComboBox"); // NOI18N

        eLProperty = ELProperty.create("${suppliers}");
        JComboBoxBinding jComboBoxBinding = SwingBindings.createJComboBoxBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, suppliersComboBox);
        bindingGroup.addBinding(jComboBoxBinding);

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(newQuotationLabel)
                    .addComponent(quantityField)
                    .addComponent(unitPriceField)
                    .addComponent(createQuotationButton)
                    .addComponent(jSeparator1)
                    .addComponent(purchaseQuotationButton, GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(suppliersComboBox, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(quotationListLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(newQuotationLabel)
                    .addComponent(quotationListLabel))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(quantityField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(unitPriceField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(suppliersComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(createQuotationButton)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(purchaseQuotationButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE))
                .addContainerGap())
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public JButton createQuotationButton;
    public JScrollPane jScrollPane1;
    public JSeparator jSeparator1;
    public JLabel newQuotationLabel;
    public JButton purchaseQuotationButton;
    public JTextField quantityField;
    public JLabel quotationListLabel;
    public JTable quotationTable;
    public JComboBox suppliersComboBox;
    public JTextField unitPriceField;
    private BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    @Override
    public Object getComponent(QuotationViewComponents component) {
        switch (component) {
            case CreateQuotationButton:
                return createQuotationButton;
            case PurchaseQuotationButton:
                return purchaseQuotationButton;
            case QuantityField:
                return bindingGroup.getBinding("quantityField");
            case Quotation:
                return quotation;
            case QuotationTable:
                return quotationTable;
            case Quotations:
                return quotations;
            case Suppliers:
                return suppliers;
            case SuppliersComboBox:
                return suppliersComboBox;
            case UnitPriceField:
                return bindingGroup.getBinding("unitPriceField");
            default:
                return null;
        }
    }
}
