package yamenko.abcgrocery.views;

import java.math.BigDecimal;
import java.sql.Date;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.LayoutStyle;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.beansbinding.ELProperty;
import org.jdesktop.observablecollections.ObservableCollections;
import org.jdesktop.observablecollections.ObservableList;
import org.jdesktop.swingbinding.JComboBoxBinding;
import org.jdesktop.swingbinding.JListBinding;
import org.jdesktop.swingbinding.JTableBinding;
import org.jdesktop.swingbinding.SwingBindings;
import yamenko.abcgrocery.entities.Product;
import yamenko.abcgrocery.entities.SaleActivity;
import yamenko.abcgrocery.views.components.SaleActivityComponents;

/**
 *
 * @author Eugene Yamenko <yamenko@me.com>
 */
public class SaleActivityView extends javax.swing.JPanel implements View<SaleActivityComponents> {
    @Override
    public Object getComponent(SaleActivityComponents component) {
        switch (component) {
            case AddProductButton:
                return addProductButton;
            case NewSaleActivityButton:
                return newSaleActivityButton;
            case Products:
                return getProducts();
            case ProductsComboBox:
                return productsComboBox;
            case SaleActivities:
                return getSaleActivities();
            case SaleActivitiesTable:
                return saleActivitiesTable;
            case SoldProducts:
                return getSoldProducts();
            default:
                return null;
        }
    }
    private ObservableList<SaleActivity> saleActivities = ObservableCollections.observableList(
            new ArrayList<SaleActivity>());
    private ObservableList<Product> products = ObservableCollections.observableList(
            new ArrayList<Product>());
    private ObservableList<Product> soldProducts = ObservableCollections.observableList(
            new ArrayList<Product>());

    public List<SaleActivity> getSaleActivities() {
        return saleActivities;
    }

    public List<Product> getProducts() {
        return products;
    }

    public List<Product> getSoldProducts() {
        return soldProducts;
    }

    /**
     * Creates new form SaleActivityView
     */
    public SaleActivityView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new BindingGroup();

        saleActivitiesListLabel = new JLabel();
        jScrollPane1 = new JScrollPane();
        saleActivitiesTable = new JTable();
        newSaleActivityButton = new JButton();
        productsComboBox = new JComboBox();
        addProductButton = new JButton();
        jScrollPane3 = new JScrollPane();
        soldProductsList = new JList();

        saleActivitiesListLabel.setText("List of the sale activities");
        saleActivitiesListLabel.setName("saleActivitiesListLabel"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        saleActivitiesTable.setName("saleActivitiesTable"); // NOI18N
        saleActivitiesTable.getTableHeader().setReorderingAllowed(false);

        ELProperty eLProperty = ELProperty.create("${saleActivities}");
        JTableBinding jTableBinding = SwingBindings.createJTableBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, saleActivitiesTable, "saleActivitiesTable");
        JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(ELProperty.create("${id}"));
        columnBinding.setColumnName("Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(ELProperty.create("${date}"));
        columnBinding.setColumnName("Date");
        columnBinding.setColumnClass(Date.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(ELProperty.create("${total}"));
        columnBinding.setColumnName("Total");
        columnBinding.setColumnClass(BigDecimal.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(saleActivitiesTable);
        if (saleActivitiesTable.getColumnModel().getColumnCount() > 0) {
            saleActivitiesTable.getColumnModel().getColumn(0).setResizable(false);
            saleActivitiesTable.getColumnModel().getColumn(1).setResizable(false);
            saleActivitiesTable.getColumnModel().getColumn(2).setResizable(false);
        }

        newSaleActivityButton.setText("New sale activity");
        newSaleActivityButton.setName("newSaleActivityButton"); // NOI18N

        productsComboBox.setModel(new DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        productsComboBox.setName("productsComboBox"); // NOI18N

        eLProperty = ELProperty.create("${products}");
        JComboBoxBinding jComboBoxBinding = SwingBindings.createJComboBoxBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, productsComboBox, "productsComboBox");
        bindingGroup.addBinding(jComboBoxBinding);

        addProductButton.setText("Add product to activity");
        addProductButton.setEnabled(false);
        addProductButton.setName("addProductButton"); // NOI18N

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        soldProductsList.setName("soldProductsList"); // NOI18N

        eLProperty = ELProperty.create("${soldProducts}");
        JListBinding jListBinding = SwingBindings.createJListBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, soldProductsList, "productsList");
        jListBinding.setDetailBinding(ELProperty.create("$${salePrice} ${id}: ${name}"));
        bindingGroup.addBinding(jListBinding);

        jScrollPane3.setViewportView(soldProductsList);

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saleActivitiesListLabel)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(newSaleActivityButton, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(productsComboBox, GroupLayout.Alignment.TRAILING, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(addProductButton, GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, 373, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(productsComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addProductButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(saleActivitiesListLabel)
                            .addComponent(newSaleActivityButton))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 403, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public JButton addProductButton;
    public JScrollPane jScrollPane1;
    public JScrollPane jScrollPane3;
    public JButton newSaleActivityButton;
    public JComboBox productsComboBox;
    public JLabel saleActivitiesListLabel;
    public JTable saleActivitiesTable;
    public JList soldProductsList;
    private BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
