package yamenko.abcgrocery.views;

import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.Binding;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.beansbinding.Bindings;
import org.jdesktop.beansbinding.ELProperty;
import org.jdesktop.observablecollections.ObservableCollections;
import org.jdesktop.observablecollections.ObservableList;
import org.jdesktop.swingbinding.JComboBoxBinding;
import org.jdesktop.swingbinding.JListBinding;
import org.jdesktop.swingbinding.JTableBinding;
import org.jdesktop.swingbinding.SwingBindings;
import yamenko.abcgrocery.entities.Product;
import yamenko.abcgrocery.entities.Supplier;
import yamenko.abcgrocery.views.components.SupplierViewComponents;

/**
 *
 * @author Eugene Yamenko <yamenko@me.com>
 */
public class SupplierView extends javax.swing.JPanel implements View<SupplierViewComponents> {
    @Override
    public Object getComponent(SupplierViewComponents component) {
        switch (component) {
            case AddProductButton:
                return addProductButton;
            case CreateSupplierButton:
                return createSupplierButton;
            case AddressFieldBinding:
                return bindingGroup.getBinding("addressField");
            case ContactPersonFieldBinding:
                return bindingGroup.getBinding("contactPersonField");
            case ContactPhoneFieldBinding:
                return bindingGroup.getBinding("contactPhoneField");
            case NameFieldBinding:
                return bindingGroup.getBinding("nameField");
            case Suppliers:
                return getSuppliers();
            case Supplier:
                return getSupplier();
            case NotSuppliedProducts:
                return getNotSuppliedProducts();
            case SuppliedProducts:
                return getSuppliedProducts();
            case SupplierTable:
                return supplierTable;
            case NotSuppliedProductsComboBox:
                return notSuppliedProductsComboBox;
            default:
                return null;
        }
    }
    private ObservableList<Supplier> suppliers = ObservableCollections.observableList(
            new ArrayList<Supplier>());
    private ObservableList<Product> suppliedProducts = ObservableCollections.observableList(
            new ArrayList<Product>());
    private ObservableList<Product> notSuppliedProducts = ObservableCollections.observableList(
            new ArrayList<Product>());
    private Supplier supplier = new Supplier();

    public List<Supplier> getSuppliers() {
        return suppliers;
    }

    public List<Product> getSuppliedProducts() {
        return suppliedProducts;
    }

    public List<Product> getNotSuppliedProducts() {
        return notSuppliedProducts;
    }

    public Supplier getSupplier() {
        return supplier;
    }

    /**
     * Creates new form SupplierView
     */
    public SupplierView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new BindingGroup();

        newSupplierLabel = new JLabel();
        nameField = new JTextField();
        addressField = new JTextField();
        contactPersonField = new JTextField();
        contactPhoneField = new JTextField();
        createSupplierButton = new JButton();
        jScrollPane1 = new JScrollPane();
        supplierTable = new JTable();
        supplierListLabel = new JLabel();
        jSeparator1 = new JSeparator();
        suppliedProductsLabel = new JLabel();
        jScrollPane2 = new JScrollPane();
        suppliedProductsList = new JList();
        addProductButton = new JButton();
        notSuppliedProductsComboBox = new JComboBox();

        setPreferredSize(new Dimension(700, 450));

        newSupplierLabel.setText("Create a new supplier");
        newSupplierLabel.setName("newSupplierLabel"); // NOI18N

        nameField.setToolTipText("Name");
        nameField.setName("nameField"); // NOI18N

        Binding binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${supplier.name}"), nameField, BeanProperty.create("text"), "nameField");
        bindingGroup.addBinding(binding);

        addressField.setToolTipText("Address");
        addressField.setName("addressField"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${supplier.address}"), addressField, BeanProperty.create("text"), "addressField");
        bindingGroup.addBinding(binding);

        contactPersonField.setToolTipText("Contact person");
        contactPersonField.setName("contactPersonField"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${supplier.contactPerson}"), contactPersonField, BeanProperty.create("text"), "contactPersonField");
        bindingGroup.addBinding(binding);

        contactPhoneField.setToolTipText("Contact phone");
        contactPhoneField.setName("contactPhoneField"); // NOI18N

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("${supplier.contactPhone}"), contactPhoneField, BeanProperty.create("text"), "contactPhoneField");
        bindingGroup.addBinding(binding);

        createSupplierButton.setText("Create");
        createSupplierButton.setEnabled(false);
        createSupplierButton.setName("createSupplierButton"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        supplierTable.setName("supplierTable"); // NOI18N
        supplierTable.getTableHeader().setReorderingAllowed(false);

        ELProperty eLProperty = ELProperty.create("${suppliers}");
        JTableBinding jTableBinding = SwingBindings.createJTableBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, supplierTable, "suppliersTable");
        JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(ELProperty.create("${id}"));
        columnBinding.setColumnName("Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(ELProperty.create("${name}"));
        columnBinding.setColumnName("Name");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(ELProperty.create("${address}"));
        columnBinding.setColumnName("Address");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(ELProperty.create("${contactPerson}"));
        columnBinding.setColumnName("Contact Person");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(ELProperty.create("${contactPhone}"));
        columnBinding.setColumnName("Contact Phone");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(supplierTable);
        if (supplierTable.getColumnModel().getColumnCount() > 0) {
            supplierTable.getColumnModel().getColumn(0).setResizable(false);
            supplierTable.getColumnModel().getColumn(0).setPreferredWidth(10);
            supplierTable.getColumnModel().getColumn(1).setResizable(false);
            supplierTable.getColumnModel().getColumn(1).setPreferredWidth(10);
            supplierTable.getColumnModel().getColumn(2).setResizable(false);
            supplierTable.getColumnModel().getColumn(3).setResizable(false);
            supplierTable.getColumnModel().getColumn(3).setPreferredWidth(10);
            supplierTable.getColumnModel().getColumn(4).setResizable(false);
        }

        supplierListLabel.setText("List of the suppliers");
        supplierListLabel.setName("supplierListLabel"); // NOI18N

        jSeparator1.setName("jSeparator1"); // NOI18N

        suppliedProductsLabel.setText("Supplied products");
        suppliedProductsLabel.setName("suppliedProductsLabel"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        suppliedProductsList.setName("suppliedProductsList"); // NOI18N

        eLProperty = ELProperty.create("${suppliedProducts}");
        JListBinding jListBinding = SwingBindings.createJListBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, suppliedProductsList, "suppliedProducts");
        jListBinding.setDetailBinding(ELProperty.create("${id}: ${name}"));
        bindingGroup.addBinding(jListBinding);

        jScrollPane2.setViewportView(suppliedProductsList);

        addProductButton.setText("Add product");
        addProductButton.setEnabled(false);
        addProductButton.setName("addProductButton"); // NOI18N

        notSuppliedProductsComboBox.setModel(new DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        notSuppliedProductsComboBox.setName("notSuppliedProductsComboBox"); // NOI18N

        eLProperty = ELProperty.create("${notSuppliedProducts}");
        JComboBoxBinding jComboBoxBinding = SwingBindings.createJComboBoxBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, notSuppliedProductsComboBox, "notSuppliedProducts");
        bindingGroup.addBinding(jComboBoxBinding);

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(newSupplierLabel)
                    .addComponent(createSupplierButton)
                    .addComponent(suppliedProductsLabel)
                    .addComponent(addProductButton)
                    .addComponent(addressField)
                    .addComponent(contactPersonField)
                    .addComponent(contactPhoneField)
                    .addComponent(jSeparator1)
                    .addComponent(notSuppliedProductsComboBox, 0, 200, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(nameField))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(supplierListLabel)
                        .addGap(0, 322, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(newSupplierLabel)
                    .addComponent(supplierListLabel))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addressField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contactPersonField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contactPhoneField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(createSupplierButton)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(suppliedProductsLabel)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(notSuppliedProductsComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addProductButton))
                    .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE))
                .addContainerGap())
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public JButton addProductButton;
    public JTextField addressField;
    public JTextField contactPersonField;
    public JTextField contactPhoneField;
    public JButton createSupplierButton;
    public JScrollPane jScrollPane1;
    public JScrollPane jScrollPane2;
    public JSeparator jSeparator1;
    public JTextField nameField;
    public JLabel newSupplierLabel;
    public JComboBox notSuppliedProductsComboBox;
    public JLabel suppliedProductsLabel;
    public JList suppliedProductsList;
    public JLabel supplierListLabel;
    public JTable supplierTable;
    private BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
